<?php

namespace AppBundle\Repository;

use AppBundle\Entity\FacebookUser;
use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param FacebookUser $user
     * @return User
     */
    public function getByFacebookUser(FacebookUser $user)
    {
        return $this->findOneByEmail($user->getGraphUser()->getEmail());
    }
}
